export const userTypes = {
    USER_SIGNUP : "USER_SIGNUP",
    USER_SIGNUP_SUCCESS : "USER_SIGNUP_SUCCESS",
    USER_SIGNUP_FAIL : "USER_SIGNUP_FAIL",

    USER_SIGNIN : "USER_SIGNIN",
    USER_SIGNIN_SUCCESS : "USER_SIGNIN_SUCCESS",
    USER_SIGNIN_FAIL : "USER_SIGNIN_FAIL",


    USER_SIGNOUT : "USER_SIGNOUT",
    USER_SIGNOUT_SUCCESS : "USER_SIGNOUT_SUCCESS",
    USER_SIGNOUT_FAIL : "USER_SIGNOUT_FAIL"
};
